version: "3.5"
services:
  mysql:
    image: mysql:8.0.3
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
       - ./mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 312156
      MYSQL_ROOT_HOST: '%'
  redis:
    image: redis:6.0-rc1-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./redis/:/data

